import Head from "next/Head";
import Layout from "../components/Layout";
import Link from "next/link";

export default function Home({ pokemon }) {
  console.log(pokemon);
  return (
    <div>
      <Head>
        <title>PokéWordle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout title="PokéWordle">
        <h1 className="text-4xl mb-8 text-center">PokéWordle</h1>
        <ul>
          {pokemon.map((pokeman, index) => (
            <li key={index}>
              <Link href={`/pokemon?id=${index + 1}`}>
                <a className="border p-4 border-gray my-2 capitalize flex items-center text-lg bg-gray-200 rounded-md">
                  <h2>{pokeman.name}</h2>
                </a>
              </Link>
            </li>
          ))}
        </ul>
      </Layout>
    </div>
  );
}

export async function getStaticProps(context) {
  try {
    const res = await fetch("https://pokeapi.co/api/v2/pokemon?limit=150");
    const { results } = await res.json();
    const pokemon = results.map((result) => {
      return {
        ...result,
      };
    });
    return {
      props: { pokemon },
    };
  } catch (err) {
    console.error(err);
  }
  return {
    props: {},
  };
}
